-libraryjars /Users/yusa/midp/WTK2.5.2/lib/mmapi.jar:/Users/yusa/midp/WTK2.5.2/lib/midpapi20.jar:/Users/yusa/midp/WTK2.5.2/lib/wma11.jar:/Users/yusa/midp/WTK2.5.2/lib/cldcapi11.jar
-injars /Users/yusa/j2mewtk/2.5.2/apps/HelloWorld/bin/HelloWorld.jar
-outjar /var/folders/4B/4Bt8kuHYFqONbup7ef0P7k+++TI/-Tmp-/HelloWorld.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
